#!bin/sh

type="$1"
module="$2"
tcl="$3"
clear
echo :extract > extscript
echo :quit >> extscript
if [ "sv" = $type ]; then

	#extract the mag file
	magic -T c035u -d null ${module} < extscript
	echo Checking cell
	check_magic_leaf_cell $module
	if [ $? != 0 ]; then
		echo check_magic_leaf_cell failed
		exit 1
	fi	
	echo Verilog simulation of $module
	ext2svmod $module
	if [ "tcl" = $tcl ]; then
		ncverilog -sv +gui +ncaccess+r -y . +libext+.sv ${module}_stim.sv +tcl+${module}.tcl
	elif [ "gui" = $tcl ]; then
		ncverilog -sv +gui +ncaccess+r -y . +libext+.sv ${module}_stim.sv
	else 
		ncverilog -sv -q -y . +libext+.sv ${module}_stim.sv
	fi
elif [ "spice" = $type ]; then

	echo Checking cell
	#extract the mag file
	magic -T c035u -d null ${module}_ld < echo ":extract
	:quit"
	check_magic_cell ${module}_ld
	if [ $? != 0 ]; then
		echo check_magic_cell failed
		exit 1
	fi
	echo HSpice Simulation of $module
	ext2sp ${module}_ld
	hspice ${module}_ld.sp
	if [ $? != 0 ]; then
		echo HSpice simulation failed
		exit 2
	fi
	c_scope -pfiles ${module}_ld.tr0
else
	echo Quick Sim Script. Use:
	echo simulate {type} {module} {opt}
	echo {type} - "sv" or "spice"
	echo {module} - the cell to simulate
	echo {opt} - "gui" or "tcl" only for sv type.
fi
rm extscript
